source "http://rubygems.org"

gem 'builder'
gem 'coderay_bash'
gem 'kramdown'
gem 'mime-types'
gem 'nokogiri'
gem 'nanoc', '3.6.3'
gem 'nanoc-toolbox'
gem 'rake'
gem 'thin', '>= 1.7.0'
gem "yajl-ruby"
gem 'sass'
gem 'bourbon'
gem 'neat'

group :development do
  gem 'listen'
  gem 'rb-fsevent'
  gem 'adsf', '>= 1.2.0'
  gem 'fssm'
  gem 'rspec'
end

gem 'pry'
