source "http://rubygems.org"

gem 'builder'
gem 'coderay_bash'
gem 'kramdown'
gem 'mime-types'
gem 'nokogiri', '>= 1.18.9'
gem 'nanoc', '3.6.3'
gem 'nanoc-toolbox', '>= 0.2.1'
gem 'rake'
gem 'thin'
gem "yajl-ruby"
gem 'sass'
gem 'bourbon', '>= 4.2.2'
gem 'neat', '>= 1.7.2'

group :development do
  gem 'listen'
  gem 'rb-fsevent'
  gem 'adsf'
  gem 'fssm'
  gem 'rspec'
end

gem 'pry'
