source "http://rubygems.org"

gem 'builder'
gem 'coderay_bash'
gem 'kramdown', '>= 2.3.0'
gem 'mime-types'
gem 'nokogiri', '>= 1.13.9'
gem 'nanoc', '3.8.0'
gem 'nanoc-toolbox'
gem 'rake', '>= 12.3.3'
gem 'thin', '>= 1.7.0'
gem "yajl-ruby", ">= 1.4.2"
gem 'sass'
gem 'bourbon'
gem 'neat'

group :development do
  gem 'listen'
  gem 'rb-fsevent'
  gem 'adsf'
  gem 'fssm'
  gem 'rspec'
end

gem 'pry'
